import 'dart:io';
import 'dart:typed_data';

import 'package:fbdb/fbdb.dart';

import '../../core/utils/phone_utils.dart';

/// Servico de banco de dados Firebird 5.
/// Armazena clientes, tentativas de envio e conversas.
class DatabaseService {
  DatabaseService._();

  static final DatabaseService instance = DatabaseService._();

  static const String _dbFolderPath = r'C:\money';
  static const String _dbFileName = 'money.fdb';
  static const String _chatVisibleFromMetaKey = 'chat_visible_from';
  static const String _firebirdHost = '127.0.0.1';
  static const int _firebirdPort = 9255;
  static const String _firebirdPrimaryRoot = r'C:\money\firebird5';
  static const Map<String, String> _runtimeFirebirdFiles = <String, String>{
    'fbclient.dll': 'fbclient.dll',
    'msvcp140.dll': 'msvcp140.dll',
    'vcruntime140.dll': 'vcruntime140.dll',
  };
  static const String _dbUser = 'money';
  static const String _dbPassword = '101812Ar@';

  FbDb? _db;

  String get _databasePath =>
      '$_dbFolderPath${Platform.pathSeparator}$_dbFileName';

  /// Retorna o banco pronto para uso.
  Future<FbDb> get database async {
    if (_db != null) {
      return _db!;
    }
    _db = await _open();
    return _db!;
  }

  Future<FbDb> _open() async {
    final dir = Directory(_dbFolderPath);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    await _prepareFirebirdClientRuntime();

    final dbFile = File(_databasePath);
    final db = await _connectOrCreateDatabase(dbExists: await dbFile.exists());
    await _ensureSchema(db);
    return db;
  }

  Future<FbDb> _connectOrCreateDatabase({required bool dbExists}) async {
    try {
      if (dbExists) {
        return await FbDb.attach(
          host: _firebirdHost,
          port: _firebirdPort,
          database: _databasePath,
          user: _dbUser,
          password: _dbPassword,
        );
      }

      return await FbDb.createDatabase(
        host: _firebirdHost,
        port: _firebirdPort,
        database: _databasePath,
        user: _dbUser,
        password: _dbPassword,
      );
    } catch (error) {
      throw StateError(
        'Nao foi possivel conectar ao Firebird em '
        '$_firebirdHost:$_firebirdPort com o usuario $_dbUser. '
        'Execute a configuracao da instancia do Money antes de abrir o app. '
        'Erro original: $error',
      );
    }
  }

  Future<void> _prepareFirebirdClientRuntime() async {
    if (!Platform.isWindows) {
      return;
    }

    final sourceRoot = await _resolveFirebirdClientRoot();
    if (sourceRoot == null) {
      throw StateError(
        'Nenhuma instalacao do Firebird 5 do Money foi encontrada em '
        '$_firebirdPrimaryRoot.',
      );
    }

    final executableDirectory = _resolveRuntimeDirectory();
    for (final entry in _runtimeFirebirdFiles.entries) {
      final source = File(
        '${sourceRoot.path}${Platform.pathSeparator}${entry.key}',
      );
      if (!await source.exists()) {
        throw StateError(
          'Arquivo obrigatorio do Firebird ausente: ${source.path}',
        );
      }

      final destination = File(
        '${executableDirectory.path}${Platform.pathSeparator}${entry.value}',
      );
      final shouldCopy =
          !await destination.exists() ||
          await destination.length() != await source.length();
      if (shouldCopy) {
        await source.copy(destination.path);
      }
    }
  }

  Future<Directory?> _resolveFirebirdClientRoot() async {
    final dir = Directory(_firebirdPrimaryRoot);
    final client = File('${dir.path}${Platform.pathSeparator}fbclient.dll');
    if (await dir.exists() && await client.exists()) {
      return dir;
    }
    return null;
  }

  Directory _resolveRuntimeDirectory() {
    final executableDirectory = File(Platform.resolvedExecutable).parent;
    final normalizedExecDir = executableDirectory.path
        .replaceAll('/', '\\')
        .toLowerCase();
    final sdkBinFragment = '\\flutter\\bin\\cache\\dart-sdk\\bin';
    if (normalizedExecDir.endsWith(sdkBinFragment)) {
      return Directory.current;
    }
    return executableDirectory;
  }

  Future<void> _ensureSchema(FbDb db) async {
    if (!await _tableExists(db, 'CLIENTES')) {
      await db.execute(
        sql: '''
          CREATE TABLE CLIENTES (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            NOME VARCHAR(255) NOT NULL,
            CARGO VARCHAR(255) DEFAULT '',
            TELEFONE VARCHAR(32) NOT NULL,
            DDD VARCHAR(8) DEFAULT '',
            IDADE INTEGER DEFAULT 0,
            MUNICIPIO VARCHAR(255) DEFAULT '',
            GENERO VARCHAR(32) DEFAULT 'Indefinido',
            PARCELAS VARCHAR(255) DEFAULT '',
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          )
        ''',
      );
    }

    if (!await _tableExists(db, 'ENVIOS')) {
      await db.execute(
        sql: '''
          CREATE TABLE ENVIOS (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CLIENTE_ID BIGINT,
            TELEFONE_COMPLETO VARCHAR(32) NOT NULL,
            NOME_CLIENTE VARCHAR(255) DEFAULT '',
            SUCESSO SMALLINT DEFAULT 0 NOT NULL,
            MENSAGEM_STATUS VARCHAR(512) DEFAULT '',
            MENSAGEM_ENVIADA VARCHAR(32765),
            TIPO VARCHAR(32) DEFAULT 'massa',
            ENVIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_ENVIOS_CLIENTE FOREIGN KEY (CLIENTE_ID)
              REFERENCES CLIENTES(ID)
          )
        ''',
      );
    }

    if (!await _tableExists(db, 'CONVERSAS')) {
      await db.execute(
        sql: '''
          CREATE TABLE CONVERSAS (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TELEFONE VARCHAR(64) NOT NULL,
            NOME_CLIENTE VARCHAR(255) DEFAULT '',
            DESTINO_ENVIO VARCHAR(255) DEFAULT '',
            DIRECAO VARCHAR(32) DEFAULT 'recebida' NOT NULL,
            CONTEUDO VARCHAR(32765) NOT NULL,
            TIPO_MSG VARCHAR(32) DEFAULT 'texto',
            REGISTRADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          )
        ''',
      );
    }

    if (!await _tableExists(db, 'APP_META')) {
      await db.execute(
        sql: '''
          CREATE TABLE APP_META (
            META_KEY VARCHAR(100) PRIMARY KEY,
            META_VALUE VARCHAR(255) NOT NULL
          )
        ''',
      );
    }

    if (!await _tableExists(db, 'MODELOS_MENSAGEM')) {
      await db.execute(
        sql: '''
          CREATE TABLE MODELOS_MENSAGEM (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            NOME VARCHAR(255) NOT NULL,
            MSG1 VARCHAR(32765) DEFAULT '',
            MSG2 VARCHAR(32765) DEFAULT '',
            MSG3 VARCHAR(32765) DEFAULT '',
            MSG4 VARCHAR(32765) DEFAULT '',
            MSG5 VARCHAR(32765) DEFAULT '',
            MSG6 VARCHAR(32765) DEFAULT '',
            CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          )
        ''',
      );
    }

    if (!await _indexExists(db, 'IDX_ENVIOS_TELEFONE')) {
      await db.execute(
        sql: 'CREATE INDEX IDX_ENVIOS_TELEFONE ON ENVIOS(TELEFONE_COMPLETO)',
      );
    }
    if (!await _indexExists(db, 'IDX_CONVERSAS_TELEFONE')) {
      await db.execute(
        sql: 'CREATE INDEX IDX_CONVERSAS_TELEFONE ON CONVERSAS(TELEFONE)',
      );
    }
    if (!await _indexExists(db, 'IDX_CONVERSAS_TELEFONE_REG')) {
      await db.execute(
        sql: '''
          CREATE INDEX IDX_CONVERSAS_TELEFONE_REG
          ON CONVERSAS(TELEFONE, REGISTRADO_EM)
        ''',
      );
    }
    if (!await _indexExists(db, 'IDX_CLIENTES_TELEFONE')) {
      await db.execute(
        sql: 'CREATE INDEX IDX_CLIENTES_TELEFONE ON CLIENTES(TELEFONE)',
      );
    }

    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'DESTINO_ENVIO',
      definition: "VARCHAR(255) DEFAULT ''",
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'MENSAGEM_ID',
      definition: "VARCHAR(128) DEFAULT ''",
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'ARQUIVO_NOME',
      definition: "VARCHAR(255) DEFAULT ''",
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'ARQUIVO_MIME',
      definition: "VARCHAR(255) DEFAULT ''",
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'ARQUIVO_TAMANHO',
      definition: 'BIGINT DEFAULT 0',
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'ARQUIVO_DADOS',
      definition: 'BLOB SUB_TYPE BINARY',
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'MEDIA_URL',
      definition: "VARCHAR(2048) DEFAULT ''",
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'LATITUDE',
      definition: 'DOUBLE PRECISION',
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'LONGITUDE',
      definition: 'DOUBLE PRECISION',
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'LOCAL_NOME',
      definition: "VARCHAR(255) DEFAULT ''",
    );
    await _ensureColumn(
      db,
      table: 'CONVERSAS',
      column: 'LOCAL_ENDERECO',
      definition: "VARCHAR(512) DEFAULT ''",
    );
    if (!await _indexExists(db, 'IDX_CONVERSAS_MSG_ID')) {
      await db.execute(
        sql: 'CREATE INDEX IDX_CONVERSAS_MSG_ID ON CONVERSAS(MENSAGEM_ID)',
      );
    }
  }

  Future<bool> _tableExists(FbDb db, String tableName) async {
    final row = await _selectOneDb(
      db,
      '''
        SELECT 1 AS FOUND
        FROM RDB\$RELATIONS
        WHERE COALESCE(RDB\$SYSTEM_FLAG, 0) = 0
          AND TRIM(RDB\$RELATION_NAME) = ?
        ROWS 1
      ''',
      parameters: [tableName.toUpperCase()],
    );
    return row != null;
  }

  Future<bool> _indexExists(FbDb db, String indexName) async {
    final row = await _selectOneDb(
      db,
      '''
        SELECT 1 AS FOUND
        FROM RDB\$INDICES
        WHERE TRIM(RDB\$INDEX_NAME) = ?
        ROWS 1
      ''',
      parameters: [indexName.toUpperCase()],
    );
    return row != null;
  }

  Future<bool> _columnExists(
    FbDb db, {
    required String table,
    required String column,
  }) async {
    final row = await _selectOneDb(
      db,
      '''
        SELECT 1 AS FOUND
        FROM RDB\$RELATION_FIELDS
        WHERE TRIM(RDB\$RELATION_NAME) = ?
          AND TRIM(RDB\$FIELD_NAME) = ?
        ROWS 1
      ''',
      parameters: [table.toUpperCase(), column.toUpperCase()],
    );
    return row != null;
  }

  Future<void> _ensureColumn(
    FbDb db, {
    required String table,
    required String column,
    required String definition,
  }) async {
    if (await _columnExists(db, table: table, column: column)) {
      return;
    }

    await db.execute(sql: 'ALTER TABLE $table ADD $column $definition');
  }

  Future<Map<String, dynamic>?> _selectOneDb(
    FbDb db,
    String sql, {
    List<dynamic> parameters = const [],
  }) async {
    final row = await db.selectOne(sql: sql, parameters: parameters);
    if (row == null) {
      return null;
    }
    return _normalizeRow(row);
  }

  Future<List<Map<String, dynamic>>> _selectAllDb(
    FbDb db,
    String sql, {
    List<dynamic> parameters = const [],
  }) async {
    final rows = await db.selectAll(sql: sql, parameters: parameters);
    return rows.map(_normalizeRow).toList();
  }

  Future<Map<String, dynamic>> _executeReturningOneDb(
    FbDb db,
    String sql, {
    List<dynamic> parameters = const [],
  }) async {
    final query = db.query();
    try {
      await query.execute(sql: sql, parameters: parameters);
      return _normalizeRow(await query.getOutputAsMap());
    } finally {
      await query.close();
    }
  }

  Map<String, dynamic> _normalizeRow(Map<String, dynamic> row) {
    final normalized = <String, dynamic>{};
    row.forEach((key, value) {
      normalized[key.toString().trim().toLowerCase()] = _normalizeValue(value);
    });
    return normalized;
  }

  dynamic _normalizeValue(dynamic value) {
    if (value is DateTime) {
      return _formatDateTime(value);
    }
    if (value is ByteBuffer) {
      return value.asUint8List();
    }
    if (value is ByteData) {
      return value.buffer.asUint8List(value.offsetInBytes, value.lengthInBytes);
    }
    if (value is TypedData) {
      return value.buffer.asUint8List(value.offsetInBytes, value.lengthInBytes);
    }
    if (value is List<int>) {
      return Uint8List.fromList(value);
    }
    return value;
  }

  int _asInt(dynamic value) {
    if (value is int) {
      return value;
    }
    if (value is num) {
      return value.toInt();
    }
    return int.tryParse(value?.toString() ?? '') ?? 0;
  }

  // CLIENTES

  /// Insere ou atualiza um cliente baseado no telefone + ddd.
  Future<int> upsertCliente({
    required String nome,
    required String cargo,
    required String telefone,
    required String ddd,
    required int idade,
    required String municipio,
    required String genero,
    required List<double> parcelas,
  }) async {
    final db = await database;
    final parcelasStr = parcelas.map((p) => p.toStringAsFixed(2)).join(';');

    final existing = await _selectOneDb(
      db,
      '''
        SELECT FIRST 1 ID
        FROM CLIENTES
        WHERE TELEFONE = ? AND DDD = ?
        ORDER BY ID DESC
      ''',
      parameters: [telefone, ddd],
    );

    if (existing != null) {
      final id = _asInt(existing['id']);
      await db.execute(
        sql: '''
          UPDATE CLIENTES
          SET NOME = ?,
              CARGO = ?,
              IDADE = ?,
              MUNICIPIO = ?,
              GENERO = ?,
              PARCELAS = ?
          WHERE ID = ?
        ''',
        parameters: [nome, cargo, idade, municipio, genero, parcelasStr, id],
      );
      return id;
    }

    final inserted = await _executeReturningOneDb(
      db,
      '''
        INSERT INTO CLIENTES (
          NOME, CARGO, TELEFONE, DDD, IDADE, MUNICIPIO, GENERO, PARCELAS
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        RETURNING ID
      ''',
      parameters: [
        nome,
        cargo,
        telefone,
        ddd,
        idade,
        municipio,
        genero,
        parcelasStr,
      ],
    );

    return _asInt(inserted['id']);
  }

  Future<String?> findClientPhoneByName(String name) async {
    final candidates = await findClientPhoneCandidatesByName(name);
    if (candidates.isEmpty) {
      return null;
    }
    return candidates.first;
  }

  Future<List<String>> findClientPhoneCandidatesByName(String name) async {
    final normalizedLookup = _normalizePersonName(name);
    if (normalizedLookup.isEmpty) {
      return const [];
    }

    final db = await database;
    final rows = await _selectAllDb(db, '''
        SELECT NOME, TELEFONE, DDD
        FROM CLIENTES
        WHERE TRIM(COALESCE(NOME, '')) <> ''
        ORDER BY ID DESC
        ROWS 500
      ''');

    final exactMatch = _pickClientPhoneMatch(
      rows: rows,
      normalizedLookup: normalizedLookup,
      allowPrefixMatch: false,
    );
    if (exactMatch.isNotEmpty) {
      return exactMatch;
    }

    return _pickClientPhoneMatch(
      rows: rows,
      normalizedLookup: normalizedLookup,
      allowPrefixMatch: true,
    );
  }

  List<String> _pickClientPhoneMatch({
    required List<Map<String, Object?>> rows,
    required String normalizedLookup,
    required bool allowPrefixMatch,
  }) {
    for (final row in rows) {
      final candidateName = _normalizePersonName(row['nome']?.toString() ?? '');
      if (candidateName.isEmpty) {
        continue;
      }

      final matches = allowPrefixMatch
          ? candidateName.startsWith(normalizedLookup) ||
                normalizedLookup.startsWith(candidateName)
          : candidateName == normalizedLookup;
      if (!matches) {
        continue;
      }

      final phone = row['telefone']?.toString() ?? '';
      final ddd = row['ddd']?.toString() ?? '';
      final candidates = _buildStoredClientPhoneCandidates(
        phone: phone,
        ddd: ddd,
      );

      if (candidates.isNotEmpty) {
        return candidates;
      }
    }

    return const [];
  }

  List<String> _buildStoredClientPhoneCandidates({
    required String phone,
    required String ddd,
  }) {
    final rawPhone = phone.replaceAll(RegExp(r'\D'), '');
    final rawDdd = ddd.replaceAll(RegExp(r'\D'), '');
    final candidates = <String>[];

    void addCandidate(String value) {
      final digits = value.replaceAll(RegExp(r'\D'), '');
      if (digits.isEmpty) {
        return;
      }

      final normalized = PhoneUtils.normalize(digits);
      if (_looksLikeStoredClientPhone(normalized) &&
          !candidates.contains(normalized)) {
        candidates.add(normalized);
      }
    }

    if (rawPhone.isEmpty) {
      return candidates;
    }

    if (rawDdd.isNotEmpty) {
      if (rawPhone.startsWith('55') || rawPhone.startsWith(rawDdd)) {
        addCandidate(rawPhone);
      } else {
        addCandidate('$rawDdd$rawPhone');
      }
    }

    addCandidate(rawPhone);
    return candidates;
  }

  bool _looksLikeStoredClientPhone(String value) {
    final digits = value.replaceAll(RegExp(r'\D'), '');
    return digits.length >= 12 && digits.length <= 13;
  }

  // ENVIOS

  /// Registra uma tentativa de envio.
  Future<int> registrarEnvio({
    int? clienteId,
    required String telefoneCompleto,
    required String nomeCliente,
    required bool sucesso,
    required String mensagemStatus,
    String mensagemEnviada = '',
    String tipo = 'massa',
  }) async {
    final db = await database;
    final inserted = await _executeReturningOneDb(
      db,
      '''
        INSERT INTO ENVIOS (
          CLIENTE_ID,
          TELEFONE_COMPLETO,
          NOME_CLIENTE,
          SUCESSO,
          MENSAGEM_STATUS,
          MENSAGEM_ENVIADA,
          TIPO
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        RETURNING ID
      ''',
      parameters: [
        clienteId,
        telefoneCompleto,
        nomeCliente,
        sucesso ? 1 : 0,
        mensagemStatus,
        mensagemEnviada,
        tipo,
      ],
    );
    return _asInt(inserted['id']);
  }

  /// Retorna os envios de hoje com sucesso.
  Future<int> countEnviosHojeSucesso() async {
    final db = await database;
    final bounds = _dayBounds(DateTime.now());
    final result = await _selectOneDb(
      db,
      '''
        SELECT COUNT(*) AS TOTAL
        FROM ENVIOS
        WHERE SUCESSO = 1
          AND ENVIADO_EM >= ?
          AND ENVIADO_EM < ?
      ''',
      parameters: [bounds.start, bounds.end],
    );
    return _asInt(result?['total']);
  }

  /// Retorna os envios de hoje com falha.
  Future<int> countEnviosHojeFalha() async {
    final db = await database;
    final bounds = _dayBounds(DateTime.now());
    final result = await _selectOneDb(
      db,
      '''
        SELECT COUNT(*) AS TOTAL
        FROM ENVIOS
        WHERE SUCESSO = 0
          AND ENVIADO_EM >= ?
          AND ENVIADO_EM < ?
      ''',
      parameters: [bounds.start, bounds.end],
    );
    return _asInt(result?['total']);
  }

  // CONVERSAS

  Future<DateTime> ensureChatVisibleFrom() async {
    final db = await database;
    final existing = await _selectOneDb(
      db,
      '''
        SELECT FIRST 1 META_VALUE
        FROM APP_META
        WHERE META_KEY = ?
      ''',
      parameters: [_chatVisibleFromMetaKey],
    );

    final parsed = _parseStoredDateTime(existing?['meta_value']?.toString());
    if (parsed != null) {
      return parsed;
    }

    final now = DateTime.now();
    await db.execute(
      sql: '''
        UPDATE OR INSERT INTO APP_META (META_KEY, META_VALUE)
        VALUES (?, ?)
        MATCHING (META_KEY)
      ''',
      parameters: [_chatVisibleFromMetaKey, _formatDateTime(now)],
    );
    return now;
  }

  /// Registra uma mensagem na conversa.
  Future<int> registrarMensagem({
    required String telefone,
    String nomeCliente = '',
    String destinoEnvio = '',
    required String direcao,
    required String conteudo,
    String tipoMsg = 'texto',
    String mensagemId = '',
    String arquivoNome = '',
    String arquivoMime = '',
    int arquivoTamanho = 0,
    Uint8List? arquivoDados,
    String mediaUrl = '',
    double? latitude,
    double? longitude,
    String localNome = '',
    String localEndereco = '',
    DateTime? registradoEm,
  }) async {
    final db = await database;
    final normalizedContent = conteudo.trim();
    final normalizedTarget = destinoEnvio.trim();
    final normalizedName = nomeCliente.trim();
    final normalizedType = tipoMsg.trim().isEmpty ? 'texto' : tipoMsg.trim();
    final normalizedMessageId = mensagemId.trim();
    final normalizedFileName = arquivoNome.trim();
    final normalizedMime = arquivoMime.trim();
    final normalizedMediaUrl = mediaUrl.trim();
    final normalizedLocationName = localNome.trim();
    final normalizedLocationAddress = localEndereco.trim();
    final hasAttachmentBytes = arquivoDados != null && arquivoDados.isNotEmpty;
    final hasRichPayload =
        normalizedType != 'texto' ||
        normalizedFileName.isNotEmpty ||
        normalizedMediaUrl.isNotEmpty ||
        hasAttachmentBytes ||
        latitude != null ||
        longitude != null ||
        normalizedLocationName.isNotEmpty ||
        normalizedLocationAddress.isNotEmpty;

    if (normalizedContent.isEmpty && !hasRichPayload) {
      throw ArgumentError('A mensagem precisa ter texto ou conteudo anexo.');
    }

    if (normalizedMessageId.isNotEmpty) {
      final existingByMessageId = await _selectOneDb(
        db,
        '''
          SELECT FIRST 1 ID
          FROM CONVERSAS
          WHERE TELEFONE = ?
            AND DIRECAO = ?
            AND MENSAGEM_ID = ?
          ORDER BY ID DESC
        ''',
        parameters: [telefone, direcao, normalizedMessageId],
      );

      if (existingByMessageId != null) {
        return _asInt(existingByMessageId['id']);
      }
    }

    if (registradoEm != null &&
        (normalizedContent.isNotEmpty || hasRichPayload)) {
      final existing = await _selectOneDb(
        db,
        '''
          SELECT FIRST 1 ID
          FROM CONVERSAS
          WHERE TELEFONE = ?
            AND DIRECAO = ?
            AND CONTEUDO = ?
            AND TIPO_MSG = ?
            AND REGISTRADO_EM = ?
          ORDER BY ID DESC
        ''',
        parameters: [
          telefone,
          direcao,
          normalizedContent,
          normalizedType,
          registradoEm,
        ],
      );

      if (existing != null) {
        final id = _asInt(existing['id']);
        if (normalizedTarget.isNotEmpty) {
          await db.execute(
            sql: '''
              UPDATE CONVERSAS
              SET DESTINO_ENVIO = ?
              WHERE ID = ?
                AND TRIM(COALESCE(DESTINO_ENVIO, '')) = ''
            ''',
            parameters: [normalizedTarget, id],
          );
        }
        return id;
      }
    }

    final inserted = await _executeReturningOneDb(
      db,
      registradoEm == null
          ? '''
              INSERT INTO CONVERSAS (
                TELEFONE,
                NOME_CLIENTE,
                DESTINO_ENVIO,
                DIRECAO,
                CONTEUDO,
                TIPO_MSG,
                MENSAGEM_ID,
                ARQUIVO_NOME,
                ARQUIVO_MIME,
                ARQUIVO_TAMANHO,
                ARQUIVO_DADOS,
                MEDIA_URL,
                LATITUDE,
                LONGITUDE,
                LOCAL_NOME,
                LOCAL_ENDERECO
              )
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
              RETURNING ID
            '''
          : '''
              INSERT INTO CONVERSAS (
                TELEFONE,
                NOME_CLIENTE,
                DESTINO_ENVIO,
                DIRECAO,
                CONTEUDO,
                TIPO_MSG,
                MENSAGEM_ID,
                ARQUIVO_NOME,
                ARQUIVO_MIME,
                ARQUIVO_TAMANHO,
                ARQUIVO_DADOS,
                MEDIA_URL,
                LATITUDE,
                LONGITUDE,
                LOCAL_NOME,
                LOCAL_ENDERECO,
                REGISTRADO_EM
              )
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
              RETURNING ID
            ''',
      parameters: registradoEm == null
          ? [
              telefone,
              normalizedName,
              normalizedTarget,
              direcao,
              normalizedContent,
              normalizedType,
              normalizedMessageId,
              normalizedFileName,
              normalizedMime,
              arquivoTamanho,
              arquivoDados,
              normalizedMediaUrl,
              latitude,
              longitude,
              normalizedLocationName,
              normalizedLocationAddress,
            ]
          : [
              telefone,
              normalizedName,
              normalizedTarget,
              direcao,
              normalizedContent,
              normalizedType,
              normalizedMessageId,
              normalizedFileName,
              normalizedMime,
              arquivoTamanho,
              arquivoDados,
              normalizedMediaUrl,
              latitude,
              longitude,
              normalizedLocationName,
              normalizedLocationAddress,
              registradoEm,
            ],
    );

    return _asInt(inserted['id']);
  }

  /// Recupera conversas de um telefone.
  Future<List<Map<String, dynamic>>> getConversas(
    String telefone, {
    DateTime? visibleFrom,
  }) async {
    final db = await database;
    return await _selectAllDb(
      db,
      '''
        SELECT
          TELEFONE,
          NOME_CLIENTE,
          DESTINO_ENVIO,
          DIRECAO,
          CONTEUDO,
          TIPO_MSG,
          MENSAGEM_ID,
          ARQUIVO_NOME,
          ARQUIVO_MIME,
          ARQUIVO_TAMANHO,
          ARQUIVO_DADOS,
          MEDIA_URL,
          LATITUDE,
          LONGITUDE,
          LOCAL_NOME,
          LOCAL_ENDERECO,
          REGISTRADO_EM
        FROM CONVERSAS
        WHERE TELEFONE = ?
        ${visibleFrom == null ? '' : 'AND REGISTRADO_EM >= ?'}
        ORDER BY REGISTRADO_EM ASC
      ''',
      parameters: visibleFrom == null ? [telefone] : [telefone, visibleFrom],
    );
  }

  /// Lista contatos que possuem ao menos uma mensagem recebida salva.
  Future<List<Map<String, dynamic>>> getChatContacts({
    DateTime? visibleFrom,
  }) async {
    final db = await database;
    final args = <dynamic>[];
    final visibleFilter = visibleFrom == null ? '' : 'AND C.REGISTRADO_EM >= ?';
    final previewFilter = visibleFrom == null
        ? ''
        : 'AND C2.REGISTRADO_EM >= ?';
    final targetFilter = visibleFrom == null ? '' : 'AND C4.REGISTRADO_EM >= ?';
    final nameFilter = visibleFrom == null ? '' : 'AND C3.REGISTRADO_EM >= ?';

    if (visibleFrom != null) {
      args.add(visibleFrom);
      args.add(visibleFrom);
      args.add(visibleFrom);
      args.add(visibleFrom);
      args.add(visibleFrom);
      args.add(visibleFrom);
      args.add(visibleFrom);
    }

    return await _selectAllDb(db, '''
        SELECT
          C.TELEFONE AS TELEFONE,
          COALESCE(
            NULLIF(
              (
                SELECT FIRST 1 C3.NOME_CLIENTE
                FROM CONVERSAS C3
                WHERE C3.TELEFONE = C.TELEFONE
                  AND TRIM(COALESCE(C3.NOME_CLIENTE, '')) <> ''
                  $nameFilter
                ORDER BY C3.REGISTRADO_EM DESC
              ),
              ''
            ),
            (
              SELECT FIRST 1 NULLIF(E.NOME_CLIENTE, '')
              FROM ENVIOS E
              WHERE E.TELEFONE_COMPLETO = C.TELEFONE
              ORDER BY E.ENVIADO_EM DESC
            ),
            C.TELEFONE
          ) AS NOME_CLIENTE,
          (
            SELECT FIRST 1 C2.CONTEUDO
            FROM CONVERSAS C2
            WHERE C2.TELEFONE = C.TELEFONE
              $previewFilter
            ORDER BY C2.REGISTRADO_EM DESC
          ) AS ULTIMA_MENSAGEM,
          (
            SELECT FIRST 1 C2.TIPO_MSG
            FROM CONVERSAS C2
            WHERE C2.TELEFONE = C.TELEFONE
              $previewFilter
            ORDER BY C2.REGISTRADO_EM DESC
          ) AS ULTIMO_TIPO_MSG,
          (
            SELECT FIRST 1 C2.ARQUIVO_NOME
            FROM CONVERSAS C2
            WHERE C2.TELEFONE = C.TELEFONE
              $previewFilter
            ORDER BY C2.REGISTRADO_EM DESC
          ) AS ULTIMO_ARQUIVO_NOME,
          (
            SELECT FIRST 1 C2.LOCAL_NOME
            FROM CONVERSAS C2
            WHERE C2.TELEFONE = C.TELEFONE
              $previewFilter
            ORDER BY C2.REGISTRADO_EM DESC
          ) AS ULTIMO_LOCAL_NOME,
          (
            SELECT FIRST 1 C4.DESTINO_ENVIO
            FROM CONVERSAS C4
            WHERE C4.TELEFONE = C.TELEFONE
              AND TRIM(COALESCE(C4.DESTINO_ENVIO, '')) <> ''
              $targetFilter
            ORDER BY C4.REGISTRADO_EM DESC
          ) AS DESTINO_ENVIO,
          MAX(C.REGISTRADO_EM) AS ULTIMA_INTERACAO
        FROM CONVERSAS C
        WHERE C.DIRECAO = 'recebida'
          $visibleFilter
        GROUP BY C.TELEFONE
        ORDER BY MAX(C.REGISTRADO_EM) DESC
      ''', parameters: args);
  }

  /// Monta a linha do tempo do chat com os disparos em massa e as conversas.
  Future<List<Map<String, dynamic>>> getConversationTimeline(
    String telefone, {
    DateTime? visibleFrom,
  }) async {
    final db = await database;
    final conversasFilter = visibleFrom == null ? '' : 'AND REGISTRADO_EM >= ?';
    final args = <dynamic>[telefone];
    if (visibleFrom != null) {
      args.add(visibleFrom);
    }
    args.add(telefone);
    final enviosFilter = visibleFrom == null ? '' : 'AND ENVIADO_EM >= ?';
    if (visibleFrom != null) {
      args.add(visibleFrom);
    }

    return await _selectAllDb(db, '''
        SELECT *
        FROM (
          SELECT
            TELEFONE,
            NOME_CLIENTE,
            DESTINO_ENVIO,
            DIRECAO,
            CONTEUDO,
            TIPO_MSG,
            MENSAGEM_ID,
            ARQUIVO_NOME,
            ARQUIVO_MIME,
            ARQUIVO_TAMANHO,
            ARQUIVO_DADOS,
            MEDIA_URL,
            LATITUDE,
            LONGITUDE,
            LOCAL_NOME,
            LOCAL_ENDERECO,
            REGISTRADO_EM
          FROM CONVERSAS
          WHERE TELEFONE = ?
            $conversasFilter

          UNION ALL

          SELECT
            TELEFONE_COMPLETO AS TELEFONE,
            NOME_CLIENTE,
            '' AS DESTINO_ENVIO,
            'enviada' AS DIRECAO,
            MENSAGEM_ENVIADA AS CONTEUDO,
            TIPO AS TIPO_MSG,
            '' AS MENSAGEM_ID,
            '' AS ARQUIVO_NOME,
            '' AS ARQUIVO_MIME,
            0 AS ARQUIVO_TAMANHO,
            NULL AS ARQUIVO_DADOS,
            '' AS MEDIA_URL,
            NULL AS LATITUDE,
            NULL AS LONGITUDE,
            '' AS LOCAL_NOME,
            '' AS LOCAL_ENDERECO,
            ENVIADO_EM AS REGISTRADO_EM
          FROM ENVIOS
          WHERE TELEFONE_COMPLETO = ?
            AND SUCESSO = 1
            AND TIPO = 'massa'
            AND TRIM(COALESCE(MENSAGEM_ENVIADA, '')) <> ''
            $enviosFilter
        ) TIMELINE
        ORDER BY REGISTRADO_EM ASC
      ''', parameters: args);
  }

  /// Recupera todos os envios de hoje.
  Future<List<Map<String, dynamic>>> getEnviosHoje() async {
    final db = await database;
    final bounds = _dayBounds(DateTime.now());
    return await _selectAllDb(
      db,
      '''
        SELECT
          ID,
          CLIENTE_ID,
          TELEFONE_COMPLETO,
          NOME_CLIENTE,
          SUCESSO,
          MENSAGEM_STATUS,
          MENSAGEM_ENVIADA,
          TIPO,
          ENVIADO_EM
        FROM ENVIOS
        WHERE ENVIADO_EM >= ?
          AND ENVIADO_EM < ?
        ORDER BY ENVIADO_EM DESC
      ''',
      parameters: [bounds.start, bounds.end],
    );
  }

  _DayBounds _dayBounds(DateTime reference) {
    final start = DateTime(reference.year, reference.month, reference.day);
    return _DayBounds(start: start, end: start.add(const Duration(days: 1)));
  }

  String _formatDateTime(DateTime value) {
    final local = value.toLocal();
    return '${local.year.toString().padLeft(4, '0')}-'
        '${local.month.toString().padLeft(2, '0')}-'
        '${local.day.toString().padLeft(2, '0')} '
        '${local.hour.toString().padLeft(2, '0')}:'
        '${local.minute.toString().padLeft(2, '0')}:'
        '${local.second.toString().padLeft(2, '0')}';
  }

  DateTime? _parseStoredDateTime(String? value) {
    if (value == null || value.trim().isEmpty) {
      return null;
    }

    return DateTime.tryParse(value.replaceFirst(' ', 'T'))?.toLocal();
  }

  String _normalizePersonName(String value) {
    var normalized = value.trim().toLowerCase();
    if (normalized.isEmpty) {
      return '';
    }

    final replacements = <String, String>{
      'á': 'a',
      'à': 'a',
      'â': 'a',
      'ã': 'a',
      'ä': 'a',
      'é': 'e',
      'è': 'e',
      'ê': 'e',
      'ë': 'e',
      'í': 'i',
      'ì': 'i',
      'î': 'i',
      'ï': 'i',
      'ó': 'o',
      'ò': 'o',
      'ô': 'o',
      'õ': 'o',
      'ö': 'o',
      'ú': 'u',
      'ù': 'u',
      'û': 'u',
      'ü': 'u',
      'ç': 'c',
    };

    replacements.forEach((source, target) {
      normalized = normalized.replaceAll(source, target);
    });

    final parts = normalized
        .split(RegExp(r'\s+'))
        .where((part) => part.isNotEmpty)
        .toList();
    if (parts.isEmpty) {
      return '';
    }

    return parts.first;
  }

  Future<void> close() async {
    if (_db == null) {
      return;
    }
    await _db!.detach();
    _db = null;
  }

  // MODELOS DE MENSAGEM

  /// Salva um modelo de mensagem no banco de dados.
  Future<int> salvarModelo({
    required String nome,
    required List<String> mensagens,
  }) async {
    final db = await database;
    final msgs = List<String>.generate(
      6,
      (i) => i < mensagens.length ? mensagens[i] : '',
    );
    final inserted = await _executeReturningOneDb(
      db,
      '''
        INSERT INTO MODELOS_MENSAGEM (NOME, MSG1, MSG2, MSG3, MSG4, MSG5, MSG6)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        RETURNING ID
      ''',
      parameters: [nome, msgs[0], msgs[1], msgs[2], msgs[3], msgs[4], msgs[5]],
    );
    return _asInt(inserted['id']);
  }

  /// Retorna todos os modelos salvos, mais recentes primeiro.
  Future<List<Map<String, dynamic>>> listarModelos() async {
    final db = await database;
    return await _selectAllDb(db, '''
      SELECT ID, NOME, MSG1, MSG2, MSG3, MSG4, MSG5, MSG6, CRIADO_EM
      FROM MODELOS_MENSAGEM
      ORDER BY CRIADO_EM DESC
    ''');
  }

  /// Remove um modelo pelo ID.
  Future<void> excluirModelo(int id) async {
    final db = await database;
    await db.execute(
      sql: 'DELETE FROM MODELOS_MENSAGEM WHERE ID = ?',
      parameters: [id],
    );
  }
}

class _DayBounds {
  const _DayBounds({required this.start, required this.end});

  final DateTime start;
  final DateTime end;
}
